# Generated by Django 5.1.3 on 2024-12-10 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover", models.ImageField(upload_to="book_cover")),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("writer", models.CharField(max_length=300)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("AE", "Academic & Education"),
                            ("AR", "Art"),
                            ("BI", "Biography"),
                            ("BC", "Business & Career"),
                            ("CY", "Children & Youth"),
                            ("EN", "Environment"),
                            ("FL", "Fiction & Literature"),
                            ("HF", "Health & Fitness"),
                            ("LI", "Lifestyle"),
                            ("PG", "Personal Growth"),
                            ("PL", "Politics & Laws"),
                            ("RE", "Religion"),
                            ("SR", "Science & Research"),
                            ("TE", "Technology"),
                        ],
                        default="AE",
                        max_length=2,
                    ),
                ),
                ("favorite", models.BooleanField()),
                ("publish_year", models.IntegerField()),
                ("pages", models.IntegerField()),
                ("keywords", models.TextField(blank=True)),
                ("id_user", models.IntegerField()),
                ("is_global", models.BooleanField(default=False)),
                ("file", models.FileField(upload_to="book_file")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_user", models.IntegerField()),
                (
                    "photo",
                    models.ImageField(
                        default="blank-profile-picture.png", upload_to="profile_images"
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
